misc

diff --git a/bin/getimg b/bin/getimg
--- a/bin/getimg
+++ b/bin/getimg
@@ -51,11 +51,9 @@ if echo "$PWD/$FILE" | grep slides >/dev/null 2>&1; then
 	curl -s -L "$CDN" > "$DIR/$NAME"
 	convert "$DIR/$NAME" -resize 1920x1080^ \
 		-gravity center -crop 1920x1080+0+0 +repage "$DIR/$NAME"
-	tinypng "$DIR/$NAME" || true # ok if it fails, give it a try tho
-	echo ".rc[<img src=\"$NAME\" style=\"height: 100%; width: 100%; object-fit: cover\">]"
+	(tinypng "$DIR/$NAME" || true)& # ok if it fails, give it a try tho
 	echo '![Image]('$NAME')'
 	echo "background-image: url($NAME)"
-	echo "background-size: cover"
 else
 	# Blog header image.
 	DIR="${PWD%%/content*}/static/media/$DATE"
@@ -63,9 +61,13 @@ else
 	curl -s -L "$CDN" > "$DIR/$NAME"
 	convert "$DIR/$NAME" -resize 1280x720^ \
 		-gravity center -crop 1280x720+0+0 +repage "$DIR/$NAME"
-	tinypng "$DIR/$NAME" || true # ok if it fails, give it a try tho
+	convert "$DIR/$NAME" -resize 500x500^ \
+		-gravity center -crop 500x500+0+0 +repage "$DIR/${NAME%%.jpg}.tn-500x500.jpg"
+	(tinypng "$DIR/$NAME" || true)& # ok if it fails, give it a try tho
+	(tinypng "$DIR/${NAME%%.jpg}.tn-500x500.jpg" || true)&
 
 	# Inject it in the front matter by printing out the credit and filename
 	echo credit: \""${IMG%%/download*}"\"
 	echo image: \""/media/$DATE/$NAME"\"
+	echo thumbnail: \""/media/$DATE/${NAME%%.jpg}.tn-500x500.jpg"\"
 fi
